swagger: "2.0"
info:
  description: Mô tả về api ...
  version: 1.0.1
  title: "Swagger for ecommerce"title:

paths: 
/api/products:
  get:
    summary: Lấy danh sách sản phẩm
    responses:
      "200":
        description: Lấy sản phẩm thành công
      "400":
        description: Không lấy được sản phẩm
